### ISSUE TITLE
Add site navigation (navbar, back buttons, sitemap etc)

### ISSUE THREAD

**Issue by Dhruv-Kolhatkar** [aniketdarp190301/WolfTrack4.0#1]
The website currently does not have a navbar. Additionally, when the user enters a section of the site, for example, Analyze Resume, there is no in-site way to return to the previous page. The user instead has to either use the browser back button or press the WolfTrack logo to go all the way back.

**Comment by shreyavaidya2311** [comment]
Created a navbar with a link to Dashboard (on clicking WolfTrack logo), Analyze Resume and Recommend Jobs which appears uniformly throughout the application.
