### ISSUE TITLE
Add dynamic tables for Wishlist, In Process, Applied and Offers

### ISSUE THREAD

**Issue by shreyavaidya2311** [aniketdarp190301/WolfTrack4.0#2]
All the data in current website is hardcoded and stored in a static table. In the application, the user is unable to edit the status of the application in the table. The user has to add all the details of a company repeatedly with every change in status (wishlist, in process, applied, offers).

**Comment by Dhruv-Kolhatkar** [comment]
Dynamic tables will allow the users to have control over their information in terms of where in the application process they are. Feature needs be added.

**Comment by shreyavaidya2311** [comment]
The dynamic tables for keeping track of the status, application date and due date of each company has been implemented. See pull request #3.
